[package]
name = "kymenu"
version = "0.1.0"
edition = "2024"

[dependencies]
ab_glyph = "0.2.32"
anyhow = "1.0.102"
bytemuck = "1.25.0"
clap = { version = "4.6.1", features = ["derive"] }
fontconfig = "0.10.2"
memfd = "0.6.5"
memmap2 = "0.9.10"
rand = "0.10.1"
regex = "1.12.4"
wayland-client = "0.31.14"
wayland-protocols = { version = "0.32.12", features = ["client"] }
wayland-protocols-wlr = { version = "0.3.12", features = ["client"] }
xkbcommon = "0.9.0"
xkeysym = "0.2.1"
